<?php

/**
 * Summer / holiday camps catalog for Brainova School.
 */
return [
    'hero' => [
        'title'       => 'Summer camp programs',
        'subtitle'    => 'One-week holiday camps for ages 6–13—digital skills, creativity, science, baking, art, and coding. Hands-on projects, small groups, and experienced mentors in a safe, fun environment.',
        'primary_cta' => [
            'label' => 'Talk to admissions',
            'route' => 'frontend.contact',
        ],
        'secondary_cta' => [
            'label' => 'Start online admission',
            'route' => 'frontend.online-admission',
        ],
    ],

    'categories' => [
        ['slug' => 'all', 'label' => 'All camps'],
        ['slug' => 'digital', 'label' => 'Digital skills'],
        ['slug' => 'creative', 'label' => 'Creative crafts'],
        ['slug' => 'science', 'label' => 'Science'],
        ['slug' => 'culinary', 'label' => 'Baking'],
        ['slug' => 'arts', 'label' => 'Art'],
        ['slug' => 'tech', 'label' => 'Coding'],
    ],

    'camps' => [
        [
            'slug'          => 'digital-skills-camp',
            'category'      => 'digital',
            'badge'         => 'Digital',
            'title'         => 'Digital Skills Camp',
            'description'   => 'Learn Canva, Excel, PowerPoint, and Word through fun, practical projects—build real documents, slides, and designs in one week.',
            'age_range'     => 'Ages 6–13',
            'grade'         => 'All levels welcome',
            'lessons'       => '1 week course',
            'duration'      => '1 week',
            'enrolled'      => 'Summer intake—limited seats',
            'price'         => 'Contact for fee',
            'accent'        => 'violet',
            'image'         => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Digital skills summer camp: Canva, Excel, PowerPoint, and Word for ages 6–13.',
            'overview'      => [
                'Campers rotate through short tutorials and guided projects—designing posters in Canva, building spreadsheets in Excel, and presenting ideas in PowerPoint.',
                'Every session ends with a saved project campers can show family, reinforcing confidence with everyday digital tools.',
            ],
            'highlights' => [
                'Canva, Excel, PowerPoint, and Word',
                'Small groups with step-by-step support',
                'Take-home digital portfolio pieces',
                'Suitable for ages 6–13',
            ],
            'format' => '1-week camp · daily structured sessions with breaks and creative challenges.',
        ],
        [
            'slug'          => 'plaster-candle-camp',
            'category'      => 'creative',
            'badge'         => 'Crafts',
            'title'         => 'Plaster Crafting & Candle Making',
            'description'   => 'Shape plaster creations and pour beautiful candles—texture, colour, and scent in a calm, creative studio atmosphere.',
            'age_range'     => 'Ages 6–13',
            'grade'         => 'All levels welcome',
            'lessons'       => '1 week course',
            'duration'      => '1 week',
            'enrolled'      => 'Summer intake—limited seats',
            'price'         => 'Contact for fee',
            'accent'        => 'rose',
            'image'         => 'https://images.unsplash.com/photo-1452860607049-958cad10aeff?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Plaster crafting and candle making holiday camp for children aged 6–13.',
            'overview'      => [
                'Learners explore moulding, carving, and finishing plaster pieces, then move into safe candle-making with supervision on heat and materials.',
                'The week finishes with a small display of finished crafts to take home.',
            ],
            'highlights' => [
                'Plaster shaping and finishing techniques',
                'Candle pouring, colour, and scent',
                'Studio safety and material care',
                'Suitable for ages 6–13',
            ],
            'format' => '1-week camp · hands-on workshop blocks with drying time between sessions.',
        ],
        [
            'slug'          => 'science-camp',
            'category'      => 'science',
            'badge'         => 'Science',
            'title'         => 'Science Camp',
            'description'   => 'Experimentation and exploration—predict, test, and discover how the world works through safe, exciting lab-style activities.',
            'age_range'     => 'Ages 6–13',
            'grade'         => 'All levels welcome',
            'lessons'       => '1 week course',
            'duration'      => '1 week',
            'enrolled'      => 'Summer intake—limited seats',
            'price'         => 'Contact for fee',
            'accent'        => 'teal',
            'image'         => 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Science summer camp with experiments and exploration for ages 6–13.',
            'overview'      => [
                'Each day features a new theme—forces, reactions, living things, or earth science—with campers recording predictions and results like young investigators.',
                'We emphasise curiosity, teamwork, and clear explanations—not just spectacular reactions.',
            ],
            'highlights' => [
                'Guided experiments every session',
                'Prediction journals and simple data charts',
                'Safety goggles and lab routines',
                'Suitable for ages 6–13',
            ],
            'format' => '1-week camp · lab blocks plus outdoor observation when weather allows.',
        ],
        [
            'slug'          => 'baking-camp',
            'category'      => 'culinary',
            'badge'         => 'Baking',
            'title'         => 'Baking Camp',
            'description'   => 'Make pizza, cookies, cupcakes, and practice icing and decoration—kitchen skills, hygiene, and creativity in every batch.',
            'age_range'     => 'Ages 6–13',
            'grade'         => 'All levels welcome',
            'lessons'       => '1 week course',
            'duration'      => '1 week',
            'enrolled'      => 'Summer intake—limited seats',
            'price'         => 'Contact for fee',
            'accent'        => 'amber',
            'image'         => 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Baking summer camp: pizza, cookies, cupcakes, and decoration for ages 6–13.',
            'overview'      => [
                'Campers learn measuring, mixing, and timing while baking savoury and sweet treats—from pizza dough to decorated cupcakes.',
                'Food safety, cleanliness, and teamwork in the kitchen are part of every lesson.',
            ],
            'highlights' => [
                'Pizza, cookies, and cupcakes',
                'Icing and decoration techniques',
                'Kitchen hygiene and safety',
                'Suitable for ages 6–13',
            ],
            'format' => '1-week camp · morning bakes with tasting and recipe cards to take home.',
        ],
        [
            'slug'          => 'mix-media-art-camp',
            'category'      => 'arts',
            'badge'         => 'Art',
            'title'         => 'Mix Media, Texture Art & Painting',
            'description'   => 'Explore mix media, texture techniques, and painting—layering materials, colour, and expression in original artworks.',
            'age_range'     => 'Ages 6–13',
            'grade'         => 'All levels welcome',
            'lessons'       => '1 week course',
            'duration'      => '1 week',
            'enrolled'      => 'Summer intake—limited seats',
            'price'         => 'Contact for fee',
            'accent'        => 'coral',
            'image'         => 'https://images.unsplash.com/photo-1460661419341-fd1ae736aeb5?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Mix media and texture art summer camp for ages 6–13.',
            'overview'      => [
                'Artists experiment with collage, impasto, brushwork, and found textures to build pieces that tell a story.',
                'The camp balances technique demos with open studio time so every child leaves with multiple finished works.',
            ],
            'highlights' => [
                'Mix media and texture exploration',
                'Painting techniques and colour mixing',
                'Personal portfolio of camp artwork',
                'Suitable for ages 6–13',
            ],
            'format' => '1-week camp · studio sessions with drying time for layered pieces.',
        ],
        [
            'slug'          => 'coding-animation-camp',
            'category'      => 'tech',
            'badge'         => 'Coding',
            'title'         => 'Coding & Animation Camp',
            'description'   => 'Coding and animation with Scratch and Game Lab—build games, stories, and animated scenes while learning logic step by step.',
            'age_range'     => 'Ages 6–13',
            'grade'         => 'All levels welcome',
            'lessons'       => '1 week course',
            'duration'      => '1 week',
            'enrolled'      => 'Summer intake—limited seats',
            'price'         => 'Contact for fee',
            'accent'        => 'indigo',
            'image'         => 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80',
            'meta_description' => 'Scratch coding and animation summer camp for ages 6–13.',
            'overview'      => [
                'Beginners start with drag-and-drop blocks in Scratch; returning campers extend projects in Game Lab with mentor checkpoints.',
                'Every camper publishes at least one playable mini-game or animated story by the end of the week.',
            ],
            'highlights' => [
                'Scratch block-based coding',
                'Game Lab projects for extension',
                'Animation and storytelling',
                'Suitable for ages 6–13',
            ],
            'format' => '1-week camp · paired programming and showcase on the final day.',
        ],
    ],

    'faqs' => [
        [
            'q' => 'What ages are summer camps for?',
            'a' => 'All listed holiday camps are designed for children aged 6–13. Younger campers receive extra scaffolding; older campers get extension challenges.',
        ],
        [
            'q' => 'How long is each camp?',
            'a' => 'Each program runs as a one-week course with daily sessions during the holiday period. Exact timetables are shared at registration.',
        ],
        [
            'q' => 'Can my child join more than one camp?',
            'a' => 'Yes, subject to schedule availability. Contact admissions to build a multi-camp plan for the summer.',
        ],
        [
            'q' => 'What should we bring?',
            'a' => 'A packed snack, water bottle, and comfortable clothes. Specialty materials are provided; we will note any extras in your confirmation email.',
        ],
    ],

    'trust' => [
        'headline' => 'Why families choose Brainova summer camps',
        'body'     => 'Safe studios, trained mentors, and projects children are proud to bring home—plus clear communication with parents every step of the way.',
    ],
];
